<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423194922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vault_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, encrypted_data TEXT NOT NULL, iv VARCHAR(24) NOT NULL, is_favorite BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_vault_entries_user_id ON vault_entries (user_id)');
        $this->addSql('ALTER TABLE vault_entries ADD CONSTRAINT FK_73E1C0FBA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE EXTENSION IF NOT EXISTS pgcrypto');
        $this->addSql('ALTER TABLE users ADD argon2_salt VARCHAR(64) DEFAULT NULL');
        $this->addSql("UPDATE users SET argon2_salt = encode(gen_random_bytes(32), 'hex') WHERE argon2_salt IS NULL");
        $this->addSql('ALTER TABLE users ALTER COLUMN argon2_salt SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN argon2_salt DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vault_entries DROP CONSTRAINT FK_73E1C0FBA76ED395');
        $this->addSql('DROP TABLE vault_entries');
        $this->addSql('ALTER TABLE users DROP argon2_salt');
    }
}
