<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423205026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vault_folders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(20) DEFAULT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_vault_folders_user_id ON vault_folders (user_id)');
        $this->addSql('ALTER TABLE vault_folders ADD CONSTRAINT FK_A02EA031A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vault_entries ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vault_entries ADD CONSTRAINT FK_73E1C0FB162CB942 FOREIGN KEY (folder_id) REFERENCES vault_folders (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_73E1C0FB162CB942 ON vault_entries (folder_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vault_folders DROP CONSTRAINT FK_A02EA031A76ED395');
        $this->addSql('DROP TABLE vault_folders');
        $this->addSql('ALTER TABLE vault_entries DROP CONSTRAINT FK_73E1C0FB162CB942');
        $this->addSql('DROP INDEX IDX_73E1C0FB162CB942');
        $this->addSql('ALTER TABLE vault_entries DROP folder_id');
    }
}
