<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423190104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, requester_name VARCHAR(255) DEFAULT NULL, message TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, requester_email VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_169017605F37A13B ON access_requests (token)');
        $this->addSql('CREATE INDEX IDX_access_request_token ON access_requests (token)');
        $this->addSql('CREATE INDEX IDX_access_request_status ON access_requests (status)');
        $this->addSql('CREATE TABLE locales (code VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, is_default BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE reset_password_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(100) NOT NULL, hashed_token VARCHAR(100) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_16646B41A76ED395 ON reset_password_requests (user_id)');
        $this->addSql('CREATE TABLE settings (setting_key VARCHAR(100) NOT NULL, value TEXT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, setting_type VARCHAR(50) NOT NULL, setting_group VARCHAR(100) DEFAULT NULL, PRIMARY KEY (setting_key))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(100) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, is_demo BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE reset_password_requests ADD CONSTRAINT FK_16646B41A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reset_password_requests DROP CONSTRAINT FK_16646B41A76ED395');
        $this->addSql('DROP TABLE access_requests');
        $this->addSql('DROP TABLE locales');
        $this->addSql('DROP TABLE reset_password_requests');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE users');
    }
}
